# site settings
title: Blog
subtitle: by Ziyi Chen
email: chenziyi0929@gmail.com
description: Welcome to Ziyi Chen's personal website<br /> I hope you enjoy it:)
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Wuhan University
city: Wuhan
state: Hubei
zip_code: 
country: <br />the People's Republic of China
phone: 158xxxxxx67

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/chenziyignite
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/ziyi_chen0929
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ZiyiChen15

# build settings
markdown: kramdown

sass:
  style: compressed
